### ISSUE TITLE
VOC 2007数据集训练loss不降

### ISSUE THREAD

**Issue by Bil369** [bubbliiiing/yolo3-pytorch#11]
尝试在VOC 2007数据集上训练，loss2个epoch后就维持在187左右了，大佬是能成功训练的吗？

**Comment by bubbliiiing** [comment]
你载入了预训练权重?

**Comment by Bil369** [comment]
是的，是预训练权重的问题吗？

**Comment by Bil369** [comment]
已解决，是自己lr_scheduler参数设置的问题，导致学习率几个epoch更新后过低。
