### ISSUE TITLE
预测图片未出现预测框

### ISSUE THREAD

**Issue by MrPan-git** [bubbliiiing/yolo3-pytorch#131]
出于训练时间的考虑，选取VOC数据集的前100张图片。同时将epochs改为50，其他的参数未改变。训练得到权重文件，利用该权重文件进行预测，最终并未显示预测框。不知道是不是数据量不够或者epochs太小的原因，目前还没有解决。

**Comment by bubbliiiing** [comment]
这边建议不要出于时间考虑
