### ISSUE TITLE
 Error(s) in loading state_dict for YoloBody问题

### ISSUE THREAD

**Issue by cqc1998** [bubbliiiing/yolo3-pytorch#145]
老师，我就是用的下载的voc数据集进行训练，训练的时候是用的预权值文件（yolo_weights），训练的时候没问题，classes path是voc _classes，训练完后把权值文件改成（best_epoch_weights），但是predict 和get_map会报错（RuntimeError: Error(s) in loading state_dict for YoloBody:）size mismatch for last_layer0.6.weight: copying a param with shape torch.Size([75, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([255, 1024, 1, 1]).
请问怎么解决？

**Comment by z1064894689** [comment]
同学 请问你问题解决了吗 我也和你一样！
