### ISSUE TITLE
Fail to load key

### ISSUE THREAD

**Issue by Jordan-Haidee** [bubbliiiing/yolo3-pytorch#149]
- error: 
  - Fail To Load Key: ['last_layer0.6.weight', 'last_layer0.6.bias', 'last_layer1.6.weight', 'last_layer1.6.bias', 'last_layer2.6.weight', 'last_layer2.6.bias'] ……
Fail To Load Key num: 6
- version
  - pytorch: 1.7.1
  - python: 3.9.6
  - cuda: 10.2

**Comment by zhosichao** [comment]
我也出现了这个问题，想问楼主解决了没有呀

**Comment by Tender-hjd** [comment]
妹有呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bubbliiiing/yolo3-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月29日(星期二) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bubbliiiing/yolo3-pytorch] Fail to load key (Issue #149)





 
我也出现了这个问题，想问楼主解决了没有呀

**Comment by bubbliiiing** [comment]
你们看看中文呀……

**Comment by STSTERANDMOMO** [comment]
解决了吗，我也碰到这个问题了

**Comment by season-1** [comment]
中文说了，head部分没有载入是正常现象，Backbone部分没有载入是错误的，
但是我这边进程直接被终端杀掉了，不知道怎么解决。
我的环境是
cuda：11.3；
python：3.8 
pytorch: 1.11.0

**Comment by bubbliiiing** [comment]
额，截图看看0 0

**Comment by season-1** [comment]
> 

抱歉，当时没有截图，在将pytorch降至1.8版本这个问题就解决了

**Comment by bubbliiiing** [comment]
OKOK

**Comment by fangweicheng6** [comment]
> 我也出现了这个问题，想问楼主解决了没有呀

我也遇到了 想问你解决没。。

**Comment by fangweicheng6** [comment]
[
![Uploading image.png…]()
](url)

**Comment by Liumj2022** [comment]
为什么pytorch: 1.4.0版本也不行？
