### ISSUE TITLE
输入图片尺寸问题

### ISSUE THREAD

**Issue by wujihua628** [bubbliiiing/yolo3-pytorch#150]
运行yolov4时，我的输入图片不是416*416，而是346*260 ,但是我并没有更改train.py的 这段代码

` input_shape     = [416, 416] `     

运行时并没有出错，请问您的代码中是有自动调整图片尺寸的代码嘛？我输入的图片尺寸和代码中的input shape 不同会怎么样呢？（注意，这种情况下并没有报错）

**Comment by wujihua628** [comment]
![image](https://user-images.githubusercontent.com/90367095/188272018-7a674679-44c5-4b7b-84c3-1418fe0b2610.png)
不好意思，刚看到，所以说输入图片的形状应该是任意的

**Comment by bubbliiiing** [comment]
ok
