### ISSUE TITLE
请问YOLOv3默认训练多少个epoch或者多少个step呢？YOLOv3的原论文非常建议，少了很多实现细节，没有找的训练多少个epoch。

### ISSUE THREAD

**Issue by luoh226** [bubbliiiing/yolo3-pytorch#162]
请问YOLOv3默认训练多少个epoch或者多少个step呢？YOLOv3的原论文非常建议，少了很多实现细节，没有找的训练多少个epoch。
官方代码是C语言看不太懂，看到v3的cfg里有这几个参数，请问是训练45000个step吗？max_batches又是什么？
max_batches = 50200
policy=steps
steps=40000,45000

**Comment by bubbliiiing** [comment]
300个

**Comment by bubbliiiing** [comment]
官方的我也不太懂

**Comment by luoh226** [comment]
好的，感谢。我按照官方的设定batch size=64，max_batches = 50200，在voc_0712下折算回epoch大约是228个，我按照230个epoch进行训练

**Comment by bubbliiiing** [comment]
OK~
