### ISSUE TITLE
About the freeze&unfreeze parameters in train.py

### ISSUE THREAD

**Issue by googlelee** [bubbliiiing/yolo3-pytorch#21]
Hello，I want to know that what principles should be followed to set the freeze and unfreeze parameters in train.py，Can you explain that. Thank you!

**Comment by bubbliiiing** [comment]
大家都是成年人可以说中文……北航的大兄弟……设置原则就是冻结了一部分权重。冻结部分只是到主干特征提取网络，因为特征提取是通用的。

**Comment by googlelee** [comment]
我的意思是设置它俩的值是遵循什么原则呢  比如默认是Freeze=25 Unfreeze=50，这个设置有没有理论根据呢  或者单纯是试出来的比较好的值？

**Comment by bubbliiiing** [comment]
只是经验而已

**Comment by googlelee** [comment]
好的  谢谢
