### ISSUE TITLE
boxloss改成ciou的问题

### ISSUE THREAD

**Issue by shenzhangzhou** [bubbliiiing/yolo3-pytorch#24]
博主，您好：
    我在尝试将这个v3版本的box的loss改成yolov4中的box的ciouloss， 用的也是您v4版本中的移植过来的，训练方式不变，但发现训练过程不稳定，loss跳动大，出来的检测结果也远不如v3, 请问您有什么好的解决方法嘛？ 谢谢。

**Comment by bubbliiiing** [comment]
emmm我不太清楚你改了什么，你可以直接把整个loss部分复制过来

**Comment by Q-amazing** [comment]
我是直接把整个loss部分复制过来，效果为75%，下降了20%

**Comment by bubbliiiing** [comment]
说明ciou可能不是很适合你的当前的情况？你有试过yolov4处理，效果呢？

**Comment by JohnFiv** [comment]
> 博主，您好： 我在尝试将这个v3版本的box的loss改成yolov4中的box的ciouloss， 用的也是您v4版本中的移植过来的，训练方式不变，但发现训练过程不稳定，loss跳动大，出来的检测结果也远不如v3, 请问您有什么好的解决方法嘛？ 谢谢。

您好，请问您是怎么解决的，我也是这样，ap比之前低了近15%，我发现，检测结果那里会有很多为负数的坐标，真心请教如何解决这个问题，谢谢！

**Comment by JohnFiv** [comment]
> 说明ciou可能不是很适合你的当前的情况？你有试过yolov4处理，效果呢？

但是里面为什么检测结果里面会有负坐标出现呢？应该是这个问题吧（我也不理解，不适合的情况，但是效果也差的太多了。。

**Comment by JohnFiv** [comment]
> 我是直接把整个loss部分复制过来，效果为75%，下降了20%

您好，请问您是怎么解决的，我也是这样，效果下降了15%，我发现检测结果里面有很多为负数的坐标。不使用ciou就不会出现

**Comment by bubbliiiing** [comment]
我感觉你改错了……直接复制是怎么复制啊

**Comment by bubbliiiing** [comment]
而且get_ignore那里，旧版应该是.data，是没有梯度的
