### ISSUE TITLE
ubuntu16.04 环境下的运行问题

### ISSUE THREAD

**Issue by chumingqian** [bubbliiiing/yolo3-pytorch#28]
@bubbliiiing  ， 您好：
                     非常感谢您的付出， 您解析的网络结构和 代码给了本人很好的帮助，  不过我有个疑问，请问的您代码 有在ubuntu 环境下测试过吗？   还是您只有在win 上运行的，然后git 上传的。
  因为在ubuntu 下 git 下来， 无法运行， 如下图中，   文件路径明明是存在的， 就是显示不存在；
经过查询， 修改了dos 格式，并且把 相对路径 改成 绝对路径， 可以运行了。

  所以 想表达的是，您 能否可以考虑 一下， 之后的上传的代码 可以在  环境ubuntu 下 运行通过，因为 个人观点，（个人原因实验室的显卡全部在linux 环境下） 如果您的代码无法在 linux  环境下运行，并且阅读， 有点小小的遗憾。
![Screenshot from 2020-08-26 20-47-43](https://user-images.githubusercontent.com/46816091/91308675-379eca80-e7e2-11ea-8336-81699059a008.png)
![Screenshot from 2020-08-26 21-16-48](https://user-images.githubusercontent.com/46816091/91308685-3bcae800-e7e2-11ea-8763-48743cc68f5e.png)

**Comment by bubbliiiing** [comment]
使用的时候注意根目录，你可以在yolo3-pytorch这个根目录，利用路径运行voc2yolo3.py，ubuntu我试过可以用，别慌
