### ISSUE TITLE
为啥mAP比官网的高出挺多的？

### ISSUE THREAD

**Issue by Qinpeng96** [bubbliiiing/yolo3-pytorch#44]
[官网的数据](https://pjreddie.com/darknet/yolo/)  mAP@0.5

Model             |            Train        |   Test        | mAP
-- | -- | --- | --

YOLOv3-320 | COCO trainval | test-dev | 51.5
-- | -- | -- | --

YOLOv3-416 | COCO trainval | test-dev | 55.3
-- | -- | -- | --

YOLOv3-608 | COCO trainval | test-dev | 57.9
-- | -- | -- | --

YOLOv3-spp | COCO trainval | test-dev | 60.6
-- | -- | -- | --

开始我觉得是不是get_mAP.py 计算的问题，于是我将生成的结果json 保存，使用cocoapi计算结果也是很高。
有点懵。。。

**Comment by bubbliiiing** [comment]
应该应该是测试集，我用的验证集

**Comment by Qinpeng96** [comment]
所嘎，谢谢解答

**Comment by Qinpeng96** [comment]
> 应该应该是测试集，我用的验证集


> 应该应该是测试集，我用的验证集

**Comment by Qinpeng96** [comment]
> 应该应该是测试集，我用的验证集

恩恩，感谢
