### ISSUE TITLE
请问为什么要计算真实框和预测框的iou，并将与其iou<阈值的置为负样本，不太理解这段代码，谢谢

### ISSUE THREAD

**Issue by Puppet97** [bubbliiiing/yolo3-pytorch#49]
anch_ious = jaccard(gt_box, pred_boxes_for_ignore)
anch_ious_max, _ = torch.max(anch_ious,dim=0)
anch_ious_max = anch_ious_max.view(pred_boxes[i].size()[:3])
noobj_mask[i][anch_ious_max>self.ignore_threshold] = 0

**Comment by soulyiran** [comment]
这是yolo作者的损失函数里面这样定义的，可以看一下论文或者yolov3的损失函数解析

**Comment by bubbliiiing** [comment]
0 0把重复度较高的预测框忽略了
