### ISSUE TITLE
代码更新

### ISSUE THREAD

**Issue by ElegantAlan** [bubbliiiing/yolo3-pytorch#68]
yolov3网络结构图中，特征高宽最小的特征层的通道数量不对，正确的输出特征层shape为[batch_size, 13, 13, 512]。代码是正确的。

在比克中修改的网络架构的参数，在代码中并没有修改啊，希望及时更新一下

**Comment by JAYCHOU2020** [comment]
我也遇到了这个问题，请问你是怎么修改的呢？？？untimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 29 and 30 in dimension 2 at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:71

**Comment by ElegantAlan** [comment]
> 我也遇到了这个问题，请问你是怎么修改的呢？？？untimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 29 and 30 in dimension 2 at C:/w/1/s/windows/pytorch/aten/src\THC/generic/THCTensorMath.cu:71
按照更改之后的架构把参数自己调通就行了

**Comment by bubbliiiing** [comment]
我怎么没看懂…我在博客的那个图下面已经说明了。
