### ISSUE TITLE
yolo_training里get_target没必要每批样本都算一次

### ISSUE THREAD

**Issue by dsp6414** [bubbliiiing/yolo3-pytorch#75]
标注边界框只要确定了，get_target对应的参考参数就确定了，如果每个批次都算一遍会延缓训练速度。

**Comment by dsp6414** [comment]
可以预先算出来，保存npy文件里，训练前加载内存cache下，训练时直接索引找出来，会加快训练速度。

**Comment by bubbliiiing** [comment]
emm其实主要还是因为要数据增强吧0  0.
