### ISSUE TITLE
训练效率和Loss函数问题

### ISSUE THREAD

**Issue by soulyiran** [bubbliiiing/yolo3-pytorch#88]
请问我在使用您的代码使用Nvidia 2080进行训练时，冻结主干网络，batch_size=16，num_workers=4，nvidia-smi显示的GPU利用率只用30-40%，这是正常的吗？有必要进行优化吗？
![截屏2021-10-31 下午4 27 12](https://user-images.githubusercontent.com/33992898/139574509-f101f65a-bcbd-47c7-b83a-c6c8578d24f9.png)
还有关于您的损失函数，我发现损失函数中关于框的回归误差往往会比概率误差要小好几个数量级，在训练初期尤为如此，很好奇这会不会对训练造成什么影响？同时我发现您在计算框的回归误差中使用的y_ture是对真实框编码后的x,y,w,h，而没有直接对x,y,w,h求均方损失:
<details>

```python
                y_true[b, k, j, i, 0] = batch_target[t, 0] - i.float()
                y_true[b, k, j, i, 1] = batch_target[t, 1] - j.float()
                y_true[b, k, j, i, 2] = math.log(batch_target[t, 2] / anchors[best_n][0])
                y_true[b, k, j, i, 3] = math.log(batch_target[t, 3] / anchors[best_n][1])
```
</details>
这样有什么用意吗？(因为我看到有的代码是直接求均方误差的)

十分期待您的回答，🙏

**Comment by bubbliiiing** [comment]
1、你的图是63啊。而且好像batch_size还可以设置的大一些
2、问题不大，可以收敛
3、肯定要先编码，目标检测都有编码的过程。

**Comment by soulyiran** [comment]
1. 截图截到了Val时候的情况，在训练时确实是只有30多一点
2. 增加batch_size并没有非常明显的改善
3. 尝试把所有的运算(NMS等)都放到了GPU上计算，显示GPU使用率有明显提升但是训练时间并没有缩短😂

**Comment by bubbliiiing** [comment]
可以试试增加num_works
