### ISSUE TITLE
No module named 'utils.dataloader'

### ISSUE THREAD

**Issue by eatxiangxaing** [bubbliiiing/yolo3-pytorch#9]
博主您好！从b站来的，我在train.py 的from utils.dataloader import yolo_dataset_collate, YoloDataset这里就报错No module named 'utils.dataloader'在百度上也搜不到所以来麻烦你，不知道怎么解决，跪求解答

**Comment by bubbliiiing** [comment]
根目录，相对目录

**Comment by eatxiangxaing** [comment]
nice！谢谢阿婆主
