### ISSUE TITLE
nets/yolo.py第83行的疑问

### ISSUE THREAD

**Issue by maskva** [bubbliiiing/yolo3-pytorch#94]
# 13,13,512 -> 13,13,256 -> 26,26,256
        x1_in = self.last_layer1_conv(out0_branch)
        x1_in = self.last_layer1_upsample(x1_in)

        # 26,26,256 + 26,26,512 -> 26,26,768
        x1_in = torch.cat([x1_in, x1], 1)
    
这里torch.cat的第二个参数为什么是1呢，不应该是拼接第三个维度吗

**Comment by bubbliiiing** [comment]
pytorch的通道在最前面，注释写最后是方便理解
